image: python:3.6

before_script:
  - pip install pipenv
  - pipenv install --dev

test:
  stage: test
  script:
    - pipenv run pytest --cov=bb8 tests/

docs:
  stage: test
  script:
    - cd docs
    - pipenv run make html

pages:
  stage: deploy
  script:
    - cd docs
    - pipenv run make html
    - mv _build/html/ ../public/
  artifacts:
    paths:
      - public
  only:
    - master

deploy:
  stage: deploy
  script:
    - gem install dpl
    - dpl --provider=heroku --app=bb8-bot --api_key=$HEROKU_API_KEY
  only:
    - master
